### ISSUE TITLE
Images and Styles don't render

### ISSUE THREAD

**Issue by brandondeweese** [amici-infotech/craft-super-pdf#4]
The correct image URL is set but the Image doesn't render. Also, no styles render. In fact, if add styles to my template, it renders the page with the pdf url. Am I missing something here? 

![Screen Shot 2020-12-10 at 7 13 43 AM](https://user-images.githubusercontent.com/18017918/101790388-3eaec780-3ab7-11eb-97c0-a0a4ada887e7.png)

**Comment by amici-infotech** [comment]
Hi @brandondeweese I think the best way is to use path instead of url. I have 2 solutions for this situations. 

1. Add setting variables:
```
isHtml5ParserEnabled: true,
isRemoteEnabled : true,
```
this will help to parse html and allow remote files to embed on your PDF. If this not works, I will suggest to change url with path.
```
{{ alias("@webroot") }}/images/hero/someimage.png
```

**Comment by brandondeweese** [comment]
That URL is generated from an asset/field path. I've made your changes, and well, it changes nothing.

This is from the source page:

`  {% set settings = {
              filename: entry.title|snake,
              type: 'url',
              isHtml5ParserEnabled: true,
              isRemoteEnabled : true,
          } %}

          {% set vars = {
          	entry : entry,
            hero:entry.hero.one(),
          } %}


          {% set url = craft.superpdf.template('blog/_pdf', settings, vars) %}`


and here's what I'm attempting to generate on the pdf page:

`<img src="{{hero.heroImage.one().url()}}" />
`
I'm really confused as to why this is so difficult.

**Comment by amici-infotech** [comment]
Hey, I am using the same code as yours and remote files are working good with me. Code I am using is:
```
{% set settings = {
	filename: entry.title|snake,
	isHtml5ParserEnabled: true,
	isRemoteEnabled : true,
	type: 'url',
} %}

{% set vars = {
	entry : entry,
} %}

{% set url = craft.superpdf.template('_pdf_code', settings, vars) %}
<a href="{{ url }}" target="_blank">Open PDF</a>
```

Under **_pdf_code** file, My code is:
```
<style type="text/css">
	h2{color: blue;}
</style>
<h2>{{ entry.title }}</h2>

{% set thumb = {
    mode: 'crop',
    width: 101,
    height: "auto",
    quality: 85,
    position: 'top-center'
} %}

{% for item in entry.image.all() %}
	<p><img src="{{ item.getUrl(thumb) }}" style="width: 250px; height: auto;"></p>
	<p><img src="{{ alias('@webroot') }}/images/{{ item.path }}" style="width: 250px; height: auto;"></p>
{% endfor %}
```

My output is this:
[this_is_test_88129.pdf](https://github.com/amici-infotech/craft-super-pdf/files/5758843/this_is_test_88129.pdf)

**Comment by brandondeweese** [comment]
Yea, I still can't get any images to work on my local machine. Is there something I have to do?

And can't get it to work on my server at all. Gettings "file_put_contents(): Filename cannot be empty". Same code. Same file. Doesn't work...

Here's the live: 
http://www.myscale.it/resources/on-premises-edge-computing-infrastructure-for-the-real-world

What am I missing here?

**Comment by amici-infotech** [comment]
I think this is happening because you dont have the cache folder set or the cache folder does not have write permission. https://www.gitmemory.com/issue/dompdf/dompdf/1971/529158180

Can you share the pdf code you are using to get this output?

**Comment by brandondeweese** [comment]
OK, I got that error to go away. But locally, I can't get any images to work and I can't get a pdf to generate if I'm not signed into the craft CP. Is this something you've seen?

**Comment by amici-infotech** [comment]
Hey, It was an issue with guests controller that is solved in v1.0.4. Please upgrade your plugin and give it a try.

**Comment by brandondeweese** [comment]
The issue was not solved. Moved onto another plugin. Doesn't really work as advertised.

**Comment by mufi-siebird** [comment]
Hey. I have solved the guest controller issue. Does pdf URL didnt work for you after upgrade?

**Comment by amici-infotech** [comment]
Hey. I have solved the guest controller issue. Does pdf URL didnt work for you after upgrade?

**Comment by MarkJDuwe** [comment]
Same issue. No CSS or images, even trying full image and style paths.

**Comment by amici-infotech** [comment]
@MarkJDuwe In some of my setups I found that in my local system SSL certificate was self signed so images and styles with https was not working. If that is the case, You can try this config in config/super-pdf.php file.

```
'streamContext' => [
    'ssl' => [
        'allow_self_signed'=> TRUE,
        'verify_peer' => FALSE,
        'verify_peer_name' => FALSE,
    ],
],
'isHtml5ParserEnabled' => true,
'isRemoteEnabled' => true,

// FOR Fonts to get copied in right dir
'fontDir' => '/tmp', // can be any path you want
'tempDir' => '/tmp', // can be any path you want
```
